name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Runs only when you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1 - Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2 - Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3 - Build & Push Docker image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/battery-anomaly-detector
        docker build -t $IMAGE_NAME:latest .
        docker push $IMAGE_NAME:latest

    # Step 4 - Deploy on EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/battery-anomaly-detector:latest
          docker stop battery-app || true
          docker rm battery-app || true
          docker run -d -p 8000:8000 --name battery-app ${{ secrets.DOCKERHUB_USERNAME }}/battery-anomaly-detector:latest
